Update main.yml
Try fail on test failure

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,6 +30,14 @@ jobs:
         uses: actions/checkout@v3
       - name: Build Writerside docs using Docker
         uses: JetBrains/writerside-github-action@v3
+      - name: Check Docker output
+        run: |
+          if [[ $(docker logs $(docker ps -q)) == *"Test failed"* ]]; then
+            echo "Test failed"
+            exit 1
+          fi
+        if: steps.docker.outcome == 'success'
+        
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
